import { createTamagui } from "@tamagui/core";
import { config as baseConfig } from "@tamagui/config";
// eslint-disable-next-line @typescript-eslint/no-var-requires
const evolgritTokens = require("./design/tokens.evolgrit.json");

const colors = evolgritTokens.colors;
const gradients = evolgritTokens.gradients;
const radii = evolgritTokens.radii;
const space = evolgritTokens.space;

const themes = {
  light: {
    bg: colors.bgApp,
    card: colors.bgSurface,
    cardSubtle: colors.bgSurfaceMuted,
    surface: colors.card,
    surface2: colors.bgSurfaceMuted,
    bubbleUser: colors.bubbleUser,
    bubbleMentor: colors.bubbleCoach,
    dividerSoft: colors.bgSurfaceMuted,
    primary: colors.text,
    text: colors.text,
    text2: colors.textSecondary,
    textDark: colors.text,
    textDark2: colors.textSecondary,
    textOnDark: colors.text,
    muted: colors.textSecondary,
    border: "transparent",
    background: colors.bgApp,
    color: colors.text,
    borderColor: "transparent",
    colorMuted: colors.textSecondary,
  },
};

const config = createTamagui({
  ...baseConfig,
  themes,
  tokens: {
    ...baseConfig.tokens,
    color: {
      ...baseConfig.tokens.color,
      bg: colors.bg,
      bgApp: colors.bgApp,
      bgSurface: colors.bgSurface,
      bgSurfaceMuted: colors.bgSurfaceMuted,
      bgInput: colors.bgInput,
      card: colors.bgSurface,
      cardSubtle: colors.bgSurfaceMuted,
      text: colors.text,
      textSecondary: colors.textSecondary,
      textHint: colors.textHint,
      disabled: colors.disabled,
      danger: colors.danger,
      success: colors.success,
      successSoft: colors.successSoft,
      info: colors.info,
      infoSoft: colors.infoSoft,
      gray2: colors.gray2,
      gray6: colors.gray6,
      progressBg: "#FFFFFF",
      progressCard: colors.bgSurface,
      progressMint: colors.surfaceLanguage,
      progressLemon: colors.surfaceJob,
      progressLavender: colors.surfaceLife,
      progressInk: colors.text,
      progressMuted: colors.textSecondary,
      a1: colors.a1,
      a2: colors.a2,
      b1: colors.b1,
      b2: colors.b2,
      job: colors.job,
      focus: colors.focus,
      surfaceLanguage: colors.surfaceLanguage,
      surfaceLife: colors.surfaceLife,
      surfaceJob: colors.surfaceJob,
      surfaceFocus: colors.surfaceFocus,
      levelA1: colors.a1,
      levelA2: colors.a2,
      levelB1: colors.b1,
      levelB2: colors.b2,
      levelJob: colors.job,
      levelFocus: colors.focus,
      bubbleCoach: colors.bubbleCoach,
      bubbleUser: colors.bubbleUser,
      ringIdle: colors.ringIdle,
      ringCoach: colors.ringCoach,
      ringRec: colors.ringRec,
      ringError: colors.ringError,
      a1Soft1: gradients.a1Soft[0],
      a1Soft2: gradients.a1Soft[1],
      a2Soft1: gradients.a2Soft[0],
      a2Soft2: gradients.a2Soft[1],
      b1Soft1: gradients.b1Soft[0],
      b1Soft2: gradients.b1Soft[1],
      b2Soft1: gradients.b2Soft[0],
      b2Soft2: gradients.b2Soft[1],
      jobSoft1: gradients.jobSoft[0],
      jobSoft2: gradients.jobSoft[1],
      focusSoft1: gradients.focusSoft[0],
      focusSoft2: gradients.focusSoft[1],
    },
    radius: {
      ...baseConfig.tokens.radius,
      r0: 0,
      r12: radii.sm,
      r16: radii.md,
      r20: 20,
      r24: radii.lg,
      r28: radii.xl,
      rCard: radii.md,
      rBubble: radii.sm,
      rPill: 999,
    },
    space: {
      ...baseConfig.tokens.space,
      s0: 0,
      s8: space["1"],
      s12: 12,
      s14: 14,
      s16: space["2"],
      s20: 20,
      s24: space["3"],
    },
  },
});

export default config;
