import type { Lesson } from "./schema";

export const A1_COURSE: Lesson[] = [
  {
    id: "a1_goodbye_evening",
    level: "A1",
    title: "Goodbye in the evening",
    capability: "goodbye_evening",
    tags: ["politeness", "daily_life"],
    steps: [
      { type: "context", text: "You are leaving in the evening." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can say this when you leave in the evening.", retry: "Try again with clearer “night”." },
      { type: "hint", text: "“Good night” is used when you leave in the evening." },
      { type: "speak_guided", sentence: "Good night." },
      { type: "done", identity: "You can now say goodbye politely in the evening." },
    ],
  },
  {
    id: "a1_introduce",
    level: "A1",
    title: "Introduce yourself",
    capability: "introduce_self",
    tags: ["social", "politeness"],
    steps: [
      { type: "context", text: "You meet someone for the first time." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can introduce yourself politely.", retry: "Try again with a clearer “My name is …”." },
      { type: "hint", text: "Keep it short: name + “Nice to meet you.”" },
      { type: "speak_guided", sentence: "Hi, my name is Daniel. Nice to meet you." },
      { type: "done", identity: "You can now introduce yourself politely." },
    ],
  },
  {
    id: "a1_ask_help",
    level: "A1",
    title: "Ask for help",
    capability: "ask_help",
    tags: ["emergency", "politeness"],
    steps: [
      { type: "context", text: "You don’t understand something." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for help politely.", retry: "Try again with a clearer “help”." },
      { type: "hint", text: "Simple and polite is enough." },
      { type: "speak_guided", sentence: "Sorry, can you help me?" },
      { type: "done", identity: "You can now ask for help politely." },
    ],
  },
  {
    id: "a1_ask_repeat",
    level: "A1",
    title: "Ask to repeat",
    capability: "ask_repeat",
    tags: ["daily_life", "confidence"],
    steps: [
      { type: "context", text: "Someone speaks too fast." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask someone to repeat.", retry: "Try again with a clearer “again”." },
      { type: "hint", text: "This is a normal sentence to use every day." },
      { type: "speak_guided", sentence: "Sorry, can you say that again?" },
      { type: "done", identity: "You can now ask someone to repeat." },
    ],
  },
  {
    id: "a1_ask_slow",
    level: "A1",
    title: "Ask to speak slowly",
    capability: "ask_slow",
    tags: ["daily_life", "confidence"],
    steps: [
      { type: "context", text: "You want to understand clearly." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask someone to speak slowly.", retry: "Try again with a clearer “slowly”." },
      { type: "hint", text: "Polite + simple works best." },
      { type: "speak_guided", sentence: "Sorry, can you speak more slowly?" },
      { type: "done", identity: "You can now ask someone to speak slowly." },
    ],
  },
  {
    id: "a1_directions_station",
    level: "A1",
    title: "Ask for directions (station)",
    capability: "ask_directions",
    tags: ["transport", "daily_life"],
    steps: [
      { type: "context", text: "You are looking for a place in town." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for directions politely.", retry: "Try again with a clearer “Where is…?”" },
      { type: "hint", text: "Start with “Excuse me” to be polite." },
      { type: "speak_guided", sentence: "Excuse me, where is the station?" },
      { type: "done", identity: "You can now ask for directions politely." },
    ],
  },
  {
    id: "a1_transport_ticket",
    level: "A1",
    title: "Buy a ticket",
    capability: "buy_ticket",
    tags: ["transport", "money"],
    steps: [
      { type: "context", text: "You want a ticket." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for a ticket.", retry: "Try again with a clearer destination." },
      { type: "hint", text: "Destination + one ticket is enough." },
      { type: "speak_guided", sentence: "One ticket to the station, please." },
      { type: "done", identity: "You can now ask for a ticket politely." },
    ],
  },
  {
    id: "a1_shop_price",
    level: "A1",
    title: "Ask for the price",
    capability: "ask_price",
    tags: ["shopping", "money"],
    steps: [
      { type: "context", text: "You are in a shop." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for the price in a shop.", retry: "Try again with a clearer “How much…?”" },
      { type: "hint", text: "Short is enough: “How much is this?”" },
      { type: "speak_guided", sentence: "How much is this?" },
      { type: "done", identity: "You can now ask for the price in a shop." },
    ],
  },
  {
    id: "a1_shop_find_item",
    level: "A1",
    title: "Find an item (supermarket)",
    capability: "find_item",
    tags: ["shopping", "daily_life"],
    steps: [
      { type: "context", text: "You need something in a supermarket." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask where to find an item.", retry: "Try again with a clearer item name." },
      { type: "hint", text: "Polite start helps: “Excuse me…”" },
      { type: "speak_guided", sentence: "Excuse me, where can I find rice?" },
      { type: "done", identity: "You can now ask where to find an item in a shop." },
    ],
  },
  {
    id: "a1_order_coffee",
    level: "A1",
    title: "Order a coffee",
    capability: "order_drink",
    tags: ["food", "daily_life"],
    steps: [
      { type: "context", text: "You are at a café." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can order a drink politely.", retry: "Try again with a clearer order." },
      { type: "hint", text: "Drink + please is enough." },
      { type: "speak_guided", sentence: "A coffee, please." },
      { type: "done", identity: "You can now order a drink politely." },
    ],
  },
  {
    id: "a1_restaurant_pay",
    level: "A1",
    title: "Ask for the bill",
    capability: "ask_bill",
    tags: ["food", "money"],
    steps: [
      { type: "context", text: "You want to pay." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for the bill.", retry: "Try again with a clearer “bill”." },
      { type: "hint", text: "Short and polite works." },
      { type: "speak_guided", sentence: "The bill, please." },
      { type: "done", identity: "You can now ask for the bill politely." },
    ],
  },
  {
    id: "a1_doctor_appointment",
    level: "A1",
    title: "Doctor: simple appointment",
    capability: "doctor_appointment",
    tags: ["health", "daily_life"],
    steps: [
      { type: "context", text: "You call a doctor’s office." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can ask for an appointment.", retry: "Try again with a clearer “appointment”." },
      { type: "hint", text: "One sentence is enough." },
      { type: "speak_guided", sentence: "I need an appointment, please." },
      { type: "done", identity: "You can now ask for a simple appointment." },
    ],
  },
  {
    id: "a1_address_spell",
    level: "A1",
    title: "Spell your name",
    capability: "spell_name",
    tags: ["identity", "forms"],
    steps: [
      { type: "context", text: "Someone asks you to spell your name." },
      { type: "speak_free", prompt: "What do you say now?" },
      { type: "feedback", ok: "You can start spelling your name.", retry: "Try again slowly." },
      { type: "hint", text: "Say: “It’s …” then letters." },
      { type: "speak_guided", sentence: "It’s D-A-N-I-E-L." },
      { type: "done", identity: "You can now spell your name when needed." },
    ],
  },
];
