export type ModuleType =
  | "pfleg_aufnahme"
  | "pfleg_schmerzen"
  | "pfleg_medikamente"
  | "pfleg_vital"
  | "pfleg_hygiene"
  | "pfleg_kommunikation";

export type TemplateKey =
  | "ASK"
  | "ACK"
  | "TOO_SHORT"
  | "NO_AUDIO"
  | "REPHRASE"
  | "REMIND_GOAL"
  | "HINT_STRUCTURE"
  | "HINT_EXAMPLE_1"
  | "HINT_EXAMPLE_2"
  | "HINT_EXAMPLE_3"
  | "CLOSING";

export const UNIVERSAL_TEMPLATES: Partial<Record<TemplateKey, string[]>> = {
  NO_AUDIO: [
    "Ich habe dich noch nicht gut gehört 🙂 Halte das Mikro etwas länger und sprich klar.",
    "Da kam wenig an. Bitte sprich etwas länger und etwas lauter.",
  ],
  TOO_SHORT: [
    "Ich habe dich noch nicht gut verstanden 🙂 Sag’s bitte in einem ganzen Satz.",
    "Sag bitte etwas länger, damit ich es sicher notieren kann.",
  ],
};

export const ALLOWED_KEYS: Record<ModuleType, Record<string, TemplateKey[]>> = {
  pfleg_aufnahme: {
    aufnahme_01_name_zimmer: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    aufnahme_02_problem: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    aufnahme_03_dringlichkeit: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    aufnahme_04_closing: ["CLOSING", "REPHRASE", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
  pfleg_schmerzen: {
    schmerz_01_ort: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    schmerz_02_skala: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    schmerz_03_dauer: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    schmerz_04_symptome: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    schmerz_05_closing: ["CLOSING", "REPHRASE", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
  pfleg_medikamente: {
    med_01_medikament: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    med_02_dosis: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    med_03_zeit: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    med_04_allergie: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
      "CLOSING",
    ],
    med_05_closing: ["CLOSING", "REPHRASE", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
  pfleg_vital: {
    vital_01_bp: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REPHRASE",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
    ],
    vital_02_puls: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
    ],
    vital_03_temp: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
      "HINT_EXAMPLE_3",
    ],
    vital_04_spo2: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    vital_05_einschaetzung: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    vital_06_closing: ["CLOSING", "REPHRASE", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
  pfleg_hygiene: {
    hyg_01_haende: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    hyg_02_handschuhe: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
    ],
    safety_03_sturz: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
    ],
    safety_04_lagerung: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
      "HINT_EXAMPLE_2",
    ],
    hyg_05_closing: ["CLOSING", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
  pfleg_kommunikation: {
    comm_01_empathie: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    comm_02_beruhigen: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    comm_03_grenze_setzen: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    comm_04_naechster_schritt: [
      "ASK",
      "ACK",
      "TOO_SHORT",
      "REMIND_GOAL",
      "HINT_STRUCTURE",
      "HINT_EXAMPLE_1",
    ],
    comm_05_closing: ["CLOSING", "REMIND_GOAL", "HINT_STRUCTURE", "HINT_EXAMPLE_1"],
  },
};

export const TEMPLATES: Record<
  ModuleType,
  Record<string, Partial<Record<TemplateKey, string>>>
> = {
  pfleg_aufnahme: {
    aufnahme_01_name_zimmer: {
      ASK: "Wie heißt der Patient und in welchem Zimmer ist er?",
      ACK: "Danke. Ich habe notiert: {patientTitle}{patientName}, Zimmer {roomNumber}.",
      REPHRASE: "Nennen Sie bitte kurz Name und Zimmernummer. Zum Beispiel: „Frau Müller, Zimmer 102.“",
      REMIND_GOAL: "Kurz zum Ziel: Wir machen gerade die Aufnahme – Name und Zimmer zuerst.",
      HINT_STRUCTURE: "Schema: „{patientTitle}{patientName}, Zimmer {roomNumber}.“",
      HINT_EXAMPLE_1: "„Frau Müller, Zimmer 102.“",
      HINT_EXAMPLE_2: "„Herr Yilmaz, Zimmer 12.“",
      HINT_EXAMPLE_3: "„Patientin Schmidt, Zimmer 3.“",
      CLOSING: "Super. Dann zum Problem in einem Satz.",
    },
    aufnahme_02_problem: {
      ASK: "Was ist das Problem? Bitte in einem Satz.",
      ACK: "Verstanden. Ich notiere: {problemShort}.",
      REPHRASE:
        "Sagen Sie bitte kurz, was los ist – ein Satz reicht. Zum Beispiel: „Starke Kopfschmerzen seit heute Morgen.“",
      REMIND_GOAL: "Wir bleiben kurz bei der Aufnahme: Was ist das Problem – in einem Satz.",
      HINT_STRUCTURE: "Schema: „{Symptom} seit {Zeit}.“ oder „{Symptom}, Stärke {leicht/mittel/stark}.“",
      HINT_EXAMPLE_1: "„Starke Bauchschmerzen seit zwei Stunden.“",
      HINT_EXAMPLE_2: "„Schwindel und Übelkeit seit heute Vormittag.“",
      HINT_EXAMPLE_3: "„Der Patient ist gestürzt und hat Schmerzen am Bein.“",
      CLOSING: "Danke. Jetzt noch kurz: Seit wann und wie dringend ist es?",
    },
    aufnahme_03_dringlichkeit: {
      ASK: "Seit wann ist das so – und wirkt es eher leicht, mittel oder stark?",
      ACK: "Okay. Ich habe notiert: {durationText}, {urgencyText}.",
      REPHRASE: "Bitte zwei Dinge: seit wann (z.B. „seit gestern“) und wie stark (leicht/mittel/stark).",
      REMIND_GOAL: "Kurz zum Ziel: Wir klären gerade die Dringlichkeit (seit wann + wie stark).",
      HINT_STRUCTURE: "Schema: „Seit {Zeit} und {leicht/mittel/stark}.“",
      HINT_EXAMPLE_1: "„Seit heute Morgen und stark.“",
      HINT_EXAMPLE_2: "„Seit zwei Tagen und mittel.“",
      HINT_EXAMPLE_3: "„Seit einer Stunde und leicht.“",
      CLOSING: "Alles klar. Ich gebe das so ans Team weiter.",
    },
    aufnahme_04_closing: {
      ASK:
        "Ich fasse kurz zusammen: {patientTitle}{patientName}, Zimmer {roomNumber}, {problemShort}, {durationText}, {urgencyText}. Stimmt das so?",
      ACK: "Perfekt, danke.",
      REPHRASE: "Kurz bestätigt: Passt die Zusammenfassung so?",
      REMIND_GOAL: "Wir schließen die Aufnahme kurz ab: einmal bestätigen.",
      HINT_STRUCTURE: "Antworten Sie einfach: „Ja, stimmt.“ oder „Nein, Zimmer ist 103.“",
      HINT_EXAMPLE_1: "„Ja, stimmt so.“",
      HINT_EXAMPLE_2: "„Fast – es ist Zimmer 103.“",
      HINT_EXAMPLE_3: "„Nein – die Schmerzen sind stark, nicht mittel.“",
      CLOSING: "Danke. Aufnahme abgeschlossen.",
    },
  },
  pfleg_schmerzen: {
    schmerz_01_ort: {
      ASK: "Wo genau tut es weh? Bitte kurz: Kopf, Bauch, Rücken oder Brust?",
      ACK: "Okay: {painLocation}.",
      REPHRASE: "Sagen Sie bitte nur den Ort: „Kopf“, „Bauch“, „Rücken“ oder „Brust“.",
      REMIND_GOAL: "Kurz zum Ziel: Wir klären gerade den Schmerzort.",
      HINT_STRUCTURE: "Antworten Sie mit einem Wort: „{Ort}“.",
      HINT_EXAMPLE_1: "„Kopf.“",
      HINT_EXAMPLE_2: "„Bauch.“",
      HINT_EXAMPLE_3: "„Rücken.“",
      CLOSING: "Danke. Jetzt die Stärke von 0 bis 10.",
    },
    schmerz_02_skala: {
      ASK: "Wie stark ist der Schmerz von 0 bis 10? (0 = kein Schmerz, 10 = sehr stark)",
      ACK: "Verstanden: {painScale}/10.",
      REPHRASE: "Nennen Sie bitte nur eine Zahl zwischen 0 und 10.",
      REMIND_GOAL: "Wir bleiben kurz bei der Übung: jetzt die Stärke als Zahl 0–10.",
      HINT_STRUCTURE: "Antworten Sie z.B.: „7“ oder „7 von 10“.",
      HINT_EXAMPLE_1: "„3 von 10.“",
      HINT_EXAMPLE_2: "„7.“",
      HINT_EXAMPLE_3: "„9 von 10.“",
      CLOSING: "Okay. Seit wann haben Sie das?",
    },
    schmerz_03_dauer: {
      ASK: "Seit wann haben Sie die Schmerzen? (z.B. seit 2 Stunden / seit gestern)",
      ACK: "Okay: {durationText}.",
      REPHRASE: "Sagen Sie bitte eine Zeitangabe: „seit … Stunden/Tagen“ oder „seit gestern/heute“.",
      REMIND_GOAL: "Kurz zum Ziel: Wir klären gerade die Dauer (seit wann).",
      HINT_STRUCTURE: "Schema: „Seit {Zeit}.“",
      HINT_EXAMPLE_1: "„Seit heute Morgen.“",
      HINT_EXAMPLE_2: "„Seit zwei Stunden.“",
      HINT_EXAMPLE_3: "„Seit gestern Abend.“",
      CLOSING: "Danke. Gibt es Begleitsymptome?",
    },
    schmerz_04_symptome: {
      ASK: "Gibt es Übelkeit, Schwindel oder Fieber?",
      ACK: "Alles klar, notiert.",
      REPHRASE: "Kurz: Übelkeit? Schwindel? Fieber? Sie können auch „nein“ sagen.",
      REMIND_GOAL: "Wir schließen den Schmerz-Check ab: Begleitsymptome ja/nein.",
      HINT_STRUCTURE: "Antworten Sie: „Ja, {Symptom}.“ oder „Nein.“",
      HINT_EXAMPLE_1: "„Nein.“",
      HINT_EXAMPLE_2: "„Ja, Schwindel.“",
      HINT_EXAMPLE_3: "„Ja, Übelkeit und Fieber.“",
      CLOSING: "Danke. Ich fasse kurz zusammen.",
    },
    schmerz_05_closing: {
      ASK: "Zusammenfassung: {painLocation}, {painScale}/10, {durationText}. Stimmt das?",
      ACK: "Danke. Wir sind fertig.",
      REPHRASE: "Kurz bestätigen: stimmt die Zusammenfassung?",
      REMIND_GOAL: "Letzter Schritt: einmal kurz bestätigen.",
      HINT_STRUCTURE: "Antworten Sie: „Ja.“ oder korrigieren Sie eine Sache.",
      HINT_EXAMPLE_1: "„Ja.“",
      HINT_EXAMPLE_2: "„Fast – es ist 6 von 10.“",
      HINT_EXAMPLE_3: "„Nein – es ist seit gestern, nicht seit heute.“",
      CLOSING: "Alles klar. Schmerz-Check abgeschlossen.",
    },
  },
  pfleg_medikamente: {
    med_01_medikament: {
      ASK: "Welche Medikamente nimmt der Patient gerade? (das wichtigste zuerst)",
      ACK: "Okay: {medName}.",
      REPHRASE: "Nennen Sie bitte den Medikamentennamen. Wenn mehrere: zuerst das wichtigste.",
      REMIND_GOAL: "Kurz zum Ziel: Wir klären gerade den Medikamentennamen.",
      HINT_STRUCTURE: "Antworten Sie z.B.: „Ibuprofen“ oder „Paracetamol“.",
      HINT_EXAMPLE_1: "„Ibuprofen.“",
      HINT_EXAMPLE_2: "„Paracetamol.“",
      HINT_EXAMPLE_3: "„Insulin.“",
      CLOSING: "Danke. Welche Dosis?",
    },
    med_02_dosis: {
      ASK: "Welche Dosis? (z.B. 400 mg oder 1 Tablette)",
      ACK: "Verstanden: {medDoseText}.",
      REPHRASE: "Sagen Sie bitte eine Dosis: mg/ml oder Anzahl Tabletten.",
      REMIND_GOAL: "Wir bleiben kurz dabei: jetzt die Dosis.",
      HINT_STRUCTURE: "Schema: „{Zahl} mg“ oder „{Zahl} Tablette(n)“.",
      HINT_EXAMPLE_1: "„400 mg.“",
      HINT_EXAMPLE_2: "„1 Tablette.“",
      HINT_EXAMPLE_3: "„500 mg.“",
      CLOSING: "Okay. Wann wurde es zuletzt genommen oder wann ist es fällig?",
    },
    med_03_zeit: {
      ASK:
        "Wann wurde es zuletzt genommen – und wann ist die nächste Gabe? (Uhrzeit oder morgens/abends)",
      ACK: "Okay: {medScheduleText}.",
      REPHRASE:
        "Sagen Sie bitte kurz den Zeitpunkt, z.B. „um 8 Uhr“ oder „morgens und abends“.",
      REMIND_GOAL: "Kurz zum Ziel: Wir klären gerade den Zeitplan.",
      HINT_STRUCTURE: "Schema: „Zuletzt {Zeit}, nächstes {Zeit}“ oder „morgens/abends“.",
      HINT_EXAMPLE_1: "„Zuletzt um 8 Uhr, wieder um 16 Uhr.“",
      HINT_EXAMPLE_2: "„Morgens und abends.“",
      HINT_EXAMPLE_3: "„Alle 6 Stunden.“",
      CLOSING: "Danke. Gibt es Allergien?",
    },
    med_04_allergie: {
      ASK: "Gibt es Allergien oder Unverträglichkeiten? (z.B. Penicillin)",
      ACK: "Alles klar: {allergiesText}.",
      REPHRASE: "Kurz: Allergien ja/nein. Wenn ja: welche?",
      REMIND_GOAL: "Wir schließen ab: einmal Allergien klären.",
      HINT_STRUCTURE: "Antworten Sie: „Keine“ oder „Ja, gegen …“",
      HINT_EXAMPLE_1: "„Keine Allergien.“",
      HINT_EXAMPLE_2: "„Ja, gegen Penicillin.“",
      HINT_EXAMPLE_3: "„Ja, Unverträglichkeit bei Ibuprofen.“",
      CLOSING: "Perfekt. Ich fasse zusammen.",
    },
    med_05_closing: {
      ASK:
        "Zusammenfassung: {medName}, {medDoseText}, {medScheduleText}, Allergien: {allergiesText}. Stimmt das?",
      ACK: "Perfekt. Danke.",
      REPHRASE: "Kurz bestätigen: stimmt die Zusammenfassung?",
      REMIND_GOAL: "Letzter Schritt: einmal kurz bestätigen.",
      HINT_STRUCTURE: "Antworten Sie: „Ja.“ oder korrigieren Sie eine Sache.",
      HINT_EXAMPLE_1: "„Ja.“",
      HINT_EXAMPLE_2: "„Fast – es sind 500 mg.“",
      HINT_EXAMPLE_3: "„Nein – Allergie gegen Penicillin.“",
      CLOSING: "Medikamenten-Check abgeschlossen.",
    },
  },
  pfleg_vital: {
    vital_01_bp: {
      ASK: "Wie ist der Blutdruck? (z.B. 120 zu 80)",
      ACK: "Okay: {vital_bp_sys}/{vital_bp_dia}.",
      REPHRASE: "Sagen Sie bitte: systolisch/diastolisch, z.B. 120/80.",
      REMIND_GOAL: "Kurz zum Ziel: Wir brauchen den Blutdruck.",
      HINT_STRUCTURE: "Schema: „{Zahl} zu {Zahl}“.",
      HINT_EXAMPLE_1: "120 zu 80",
      HINT_EXAMPLE_2: "140 zu 90",
      HINT_EXAMPLE_3: "110 zu 70",
    },
    vital_02_puls: {
      ASK: "Wie ist der Puls?",
      ACK: "Notiert: {vital_pulse}.",
      REMIND_GOAL: "Kurz zum Ziel: Wir brauchen den Puls.",
      HINT_STRUCTURE: "Nennen Sie nur die Zahl.",
      HINT_EXAMPLE_1: "72",
      HINT_EXAMPLE_2: "95",
      HINT_EXAMPLE_3: "110",
    },
    vital_03_temp: {
      ASK: "Wie ist die Temperatur?",
      ACK: "Okay: {vital_temp} °C.",
      REMIND_GOAL: "Kurz zum Ziel: Wir brauchen die Temperatur.",
      HINT_STRUCTURE: "Nennen Sie nur die Zahl.",
      HINT_EXAMPLE_1: "36,8",
      HINT_EXAMPLE_2: "38,2",
      HINT_EXAMPLE_3: "39,0",
    },
    vital_04_spo2: {
      ASK: "Wie ist die Sauerstoffsättigung (SpO₂)?",
      ACK: "Okay: {vital_spo2} %.",
      REMIND_GOAL: "Kurz zum Ziel: Wir brauchen die SpO₂.",
      HINT_STRUCTURE: "Nennen Sie nur die Zahl in Prozent.",
      HINT_EXAMPLE_1: "96",
    },
    vital_05_einschaetzung: {
      ASK: "Ist etwas auffällig? (ja/nein)",
      ACK: "Verstanden: {vital_concern}.",
      REMIND_GOAL: "Kurz zum Ziel: Wir prüfen, ob Werte auffällig sind.",
      HINT_STRUCTURE: "Antworten Sie: „Ja“ oder „Nein“.",
      HINT_EXAMPLE_1: "Nein.",
    },
    vital_06_closing: {
      ASK: "Zusammenfassung: BD {bp}, Puls {vital_pulse}, Temp {vital_temp}, SpO₂ {vital_spo2}. Stimmt das?",
      CLOSING: "Danke. Vitalzeichen-Check abgeschlossen.",
      REMIND_GOAL: "Letzter Schritt: kurz bestätigen.",
      HINT_STRUCTURE: "Antworten Sie: „Ja, stimmt.“ oder korrigieren Sie eine Zahl.",
      HINT_EXAMPLE_1: "„Ja, stimmt.“",
    },
  },
  pfleg_hygiene: {
    hyg_01_haende: {
      ASK: "Was machen Sie zuerst, bevor Sie den Patienten anfassen?",
      ACK: "Genau: {hygiene_action}.",
      REMIND_GOAL: "Kurz zum Ziel: Wir starten mit Hygiene.",
      HINT_STRUCTURE: "Antworten Sie mit einer Aktion.",
      HINT_EXAMPLE_1: "Hände desinfizieren.",
    },
    hyg_02_handschuhe: {
      ASK: "Wann brauchen Sie Handschuhe?",
      ACK: "Okay: {reason_short}.",
      REMIND_GOAL: "Kurz zum Ziel: Wann Handschuhe nötig sind.",
      HINT_STRUCTURE: "Antworten Sie kurz mit einem Grund.",
      HINT_EXAMPLE_1: "Bei Körperflüssigkeiten.",
      HINT_EXAMPLE_2: "Bei Wundversorgung.",
    },
    safety_03_sturz: {
      ASK: "Was sagen Sie, damit der Patient sicher aufsteht?",
      ACK: "Gut: {safety_action}.",
      REMIND_GOAL: "Kurz zum Ziel: Sturz verhindern.",
      HINT_STRUCTURE: "Antworten Sie mit einem kurzen Satz.",
      HINT_EXAMPLE_1: "Bitte warten, ich helfe Ihnen.",
      HINT_EXAMPLE_2: "Nicht alleine aufstehen.",
    },
    safety_04_lagerung: {
      ASK: "Was prüfen Sie am Bett, damit es sicher ist?",
      ACK: "Notiert: {safety_action}.",
      REMIND_GOAL: "Kurz zum Ziel: Sicherheit am Bett.",
      HINT_STRUCTURE: "Antworten Sie mit einem Stichwort.",
      HINT_EXAMPLE_1: "Klingel erreichbar.",
      HINT_EXAMPLE_2: "Bremse drin.",
    },
    hyg_05_closing: {
      CLOSING: "Perfekt. Hygiene & Sicherheit abgeschlossen.",
      REMIND_GOAL: "Wir schließen kurz ab.",
      HINT_STRUCTURE: "Antworten Sie kurz: „Okay.“",
      HINT_EXAMPLE_1: "Okay.",
    },
  },
  pfleg_kommunikation: {
    comm_01_empathie: {
      ASK: "Sagen Sie einen empathischen Satz.",
      ACK: "Sehr gut.",
      REMIND_GOAL: "Kurz zum Ziel: Empathie zeigen.",
      HINT_STRUCTURE: "Antworten Sie mit einem Satz.",
      HINT_EXAMPLE_1: "Ich verstehe, dass das unangenehm ist.",
    },
    comm_02_beruhigen: {
      ASK: "Wie beruhigen Sie die Situation in einem Satz?",
      ACK: "Sehr gut.",
      REMIND_GOAL: "Kurz zum Ziel: ruhig beruhigen.",
      HINT_STRUCTURE: "Antworten Sie mit einem Satz.",
      HINT_EXAMPLE_1: "Wir kümmern uns gleich darum.",
    },
    comm_03_grenze_setzen: {
      ASK: "Wie setzen Sie ruhig eine Grenze?",
      ACK: "Sehr gut.",
      REMIND_GOAL: "Kurz zum Ziel: ruhig Grenzen setzen.",
      HINT_STRUCTURE: "Antworten Sie mit einem Satz.",
      HINT_EXAMPLE_1: "Bitte sprechen Sie leiser. Ich helfe Ihnen dann besser.",
    },
    comm_04_naechster_schritt: {
      ASK: "Was passiert als nächstes? (kurz erklären)",
      ACK: "Sehr gut.",
      REMIND_GOAL: "Kurz zum Ziel: nächster Schritt.",
      HINT_STRUCTURE: "Antworten Sie mit einem Satz.",
      HINT_EXAMPLE_1: "Ich messe jetzt die Werte und hole dann den Arzt.",
    },
    comm_05_closing: {
      CLOSING: "Perfekt. Kommunikation abgeschlossen.",
      REMIND_GOAL: "Wir schließen kurz ab.",
      HINT_STRUCTURE: "Antworten Sie kurz: „Okay.“",
      HINT_EXAMPLE_1: "Okay.",
    },
  },
};

export function renderTemplate(text: string, slots: Record<string, any>) {
  const replacements: Record<string, string> = {
    patientTitle: slots.patientTitle ? `${slots.patientTitle} ` : "",
    patientName: slots.patientName ?? "",
    roomNumber: slots.roomNumber ?? "",
    problemShort: slots.problemShort ?? "",
    durationText: slots.durationText ?? "",
    urgencyText: slots.urgencyText ?? "",
    painLocation: slots.painLocation ?? "",
    painScale: slots.painScale != null ? String(slots.painScale) : "",
    medName: slots.medName ?? "",
    medDoseText: slots.medDoseText ?? "",
    medScheduleText: slots.medScheduleText ?? slots.timeText ?? "",
    allergiesText: slots.allergiesText ?? "",
    vital_bp_sys: slots.vital_bp_sys ?? "",
    vital_bp_dia: slots.vital_bp_dia ?? "",
    vital_pulse: slots.vital_pulse ?? "",
    vital_temp: slots.vital_temp ?? "",
    vital_spo2: slots.vital_spo2 ?? "",
    vital_concern: slots.vital_concern ?? "",
    hygiene_action: slots.hygiene_action ?? "",
    safety_action: slots.safety_action ?? "",
    reason_short: slots.reason_short ?? "",
    bp:
      slots.vital_bp_sys && slots.vital_bp_dia
        ? `${slots.vital_bp_sys}/${slots.vital_bp_dia}`
        : "",
  };
  return text.replace(/\{(\w+)\}/g, (_match, key) => replacements[key] ?? "");
}
